### ISSUE TITLE
Should drop gas building requests for towns which have no geysers available

### ISSUE THREAD

**Issue by neivv** [neivv/aise#1]

**Comment by RdeRenato3D** [comment]
that is not implanted in the same AI? I never set the "Refinery", "Extractor" option and the AI built them anyway (although when I don't indicate it they don't seem to extract it (?)

**Comment by neivv** [comment]
Yes AI builds gas without asking and can handle mineral only towns, but if a script explicitly requests to build gas buildings at a base which has no gas, it'll hang the entire AI.
